version: "3"
services:
  app:
    container_name: express_server
    build: ./server
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb
    networks:
      - book-store
  mongodb:
    image: mongo
    volumes:
      - express_app_db:/data/db
    ports:
      - "27017:27017"
    command: mongod
    networks:
      - book-store
volumes:
  express_app_db:
  config:
networks:
  book-store:
    driver: bridge
