services:
  admin-client:
    image: node:18
    container_name: admin_client
    environment:
      - VITE_APP_ENDPOINT=http://0.0.0.0:3000
    ports:
      - 3001:3001
    working_dir: /app
    volumes:
      - ./admin-client:/app:z
    depends_on:
      - app
    command: bash -c "npm i && npm run dev"
    networks:
      - book-store
    tty: true

  customer-client:
    image: node:18
    container_name: customer_client
    environment:
      - VITE_APP_ENDPOINT=http://express_server:3000
    ports:
      - 3002:3002
    working_dir: /app
    volumes:
      - ./customer-client:/app:z
    depends_on:
      - app
    command: bash -c "npm i && npm run dev"
    networks:
      - book-store
    tty: true

  app:
    image: node:18
    container_name: express_server
    # build: ./server
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./server:/app:z
    environment:
      - MONGO_CONNECTION=mongodb://mongodb:27017/bookstore
    depends_on:
      - mongodb
    command: bash -c "npm i && npm run dev"
    networks:
      - book-store


  mongodb:
    image: mongo
    container_name: database
    volumes:
      - express_app_db:/data/db
    ports:
      - "27017:27017"
    command: mongod
    networks:
      - book-store
volumes:
  express_app_db:
  config:
networks:
  book-store:
    driver: bridge
